patterns:
  banner:
    fields:
      - name: heading
        type: string
        example: "Shop Now"
        required: false
      - name: text
        type: string
        example: "Shop all: I-phone, Samsung, Tablet, Laptop"
        required: false
